=head1 NAME

nbd_get_tls_verify_peer - get whether we verify the identity of the
server

=head1 SYNOPSIS

 #include <libnbd.h>

 int nbd_get_tls_verify_peer (
       struct nbd_handle *h
     );

=head1 DESCRIPTION

Get the verify peer flag.

=head1 RETURN VALUE

This call returns a boolean value.

=head1 ERRORS

This function does not fail.

The following parameters must not be NULL: C<h>.
For more information see L<libnbd(3)/Non-NULL parameters>.

=head1 VERSION

This function first appeared in libnbd 1.0.

If you need to test if this function is available at compile time
check if the following macro is defined:

 #define LIBNBD_HAVE_NBD_GET_TLS_VERIFY_PEER 1

=head1 SEE ALSO

L<nbd_create(3)>,
L<nbd_set_tls_verify_peer(3)>,
L<libnbd(3)>.

=head1 AUTHORS

Eric Blake

Richard W.M. Jones

=head1 COPYRIGHT

Copyright Red Hat
