=head1 NAME

nbd_set_handle_name - set the handle name

=head1 SYNOPSIS

 #include <libnbd.h>

 int nbd_set_handle_name (
       struct nbd_handle *h, const char *handle_name
     );

=head1 DESCRIPTION

Handles have a name which is unique within the current process.
The handle name is used in debug output.

Handle names are normally generated automatically and have the
form C<"nbd1">, C<"nbd2">, etc., but you can optionally use
this call to give the handles a name which is meaningful for
your application to make debugging output easier to understand.

=head1 RETURN VALUE

If the call is successful the function returns C<0>.

=head1 ERRORS

On error C<-1> is returned.

Refer to L<libnbd(3)/ERROR HANDLING>
for how to get further details of the error.

The following parameters must not be NULL: C<h>, C<handle_name>.
For more information see L<libnbd(3)/Non-NULL parameters>.

=head1 VERSION

This function first appeared in libnbd 1.0.

If you need to test if this function is available at compile time
check if the following macro is defined:

 #define LIBNBD_HAVE_NBD_SET_HANDLE_NAME 1

=head1 SEE ALSO

L<nbd_create(3)>,
L<nbd_get_handle_name(3)>,
L<libnbd(3)>.

=head1 AUTHORS

Eric Blake

Richard W.M. Jones

=head1 COPYRIGHT

Copyright Red Hat
