=head1 NAME

nbd_supports_tls - true if libnbd was compiled with support for TLS

=head1 SYNOPSIS

 #include <libnbd.h>

 int nbd_supports_tls (
       struct nbd_handle *h
     );

=head1 DESCRIPTION

Returns true if libnbd was compiled with gnutls which is required
to support TLS encryption, or false if not.

=head1 RETURN VALUE

This call returns a boolean value.

=head1 ERRORS

This function does not fail.

The following parameters must not be NULL: C<h>.
For more information see L<libnbd(3)/Non-NULL parameters>.

=head1 VERSION

This function first appeared in libnbd 1.0.

If you need to test if this function is available at compile time
check if the following macro is defined:

 #define LIBNBD_HAVE_NBD_SUPPORTS_TLS 1

=head1 SEE ALSO

L<nbd_create(3)>,
L<nbd_set_tls(3)>,
L<libnbd(3)>.

=head1 AUTHORS

Eric Blake

Richard W.M. Jones

=head1 COPYRIGHT

Copyright Red Hat
