=head1 NAME

nbd_get_structured_replies_negotiated - see if structured replies are
in use

=head1 SYNOPSIS

 #include <libnbd.h>

 int nbd_get_structured_replies_negotiated (
       struct nbd_handle *h
     );

=head1 DESCRIPTION

After connecting you may call this to find out if the connection is
using structured replies.  Note that this setting is sticky; this
can return true even after a second L<nbd_opt_structured_reply(3)>
returns false because the server detected a duplicate request.

Note that if the connection negotiates extended headers, this
function returns true (as extended headers imply structured
replies) even if no explicit request for structured replies was
attempted.

=head1 RETURN VALUE

This call returns a boolean value.

=head1 ERRORS

On error C<-1> is returned.

Refer to L<libnbd(3)/ERROR HANDLING>
for how to get further details of the error.

The following parameters must not be NULL: C<h>.
For more information see L<libnbd(3)/Non-NULL parameters>.

=head1 HANDLE STATE

The handle must be
negotiating, or
connected with the server, or
shut down,
otherwise this call will return an error.

=head1 VERSION

This function first appeared in libnbd 1.2.

If you need to test if this function is available at compile time
check if the following macro is defined:

 #define LIBNBD_HAVE_NBD_GET_STRUCTURED_REPLIES_NEGOTIATED 1

=head1 SEE ALSO

L<nbd_create(3)>,
L<nbd_get_extended_headers_negotiated(3)>,
L<nbd_get_protocol(3)>,
L<nbd_get_request_structured_replies(3)>,
L<nbd_opt_extended_headers(3)>,
L<nbd_opt_structured_reply(3)>,
L<nbd_set_request_structured_replies(3)>,
L<libnbd(3)>.

=head1 AUTHORS

Eric Blake

Richard W.M. Jones

=head1 COPYRIGHT

Copyright Red Hat
