=head1 NAME

nbd_get_package_name - return the name of the library

=head1 SYNOPSIS

 #include <libnbd.h>

 const char * nbd_get_package_name (
                struct nbd_handle *h
              );

=head1 DESCRIPTION

Returns the name of the library, always C<"libnbd"> unless
the library was modified with another name at compile time.

=head1 RETURN VALUE

This call returns a statically allocated string, valid for the
lifetime of the process or until libnbd is unloaded by
L<dlclose(3)>.  You B<must not> try to free the string.

=head1 ERRORS

This function does not fail.

The following parameters must not be NULL: C<h>.
For more information see L<libnbd(3)/Non-NULL parameters>.

=head1 VERSION

This function first appeared in libnbd 1.0.

If you need to test if this function is available at compile time
check if the following macro is defined:

 #define LIBNBD_HAVE_NBD_GET_PACKAGE_NAME 1

=head1 SEE ALSO

L<nbd_create(3)>,
L<nbd_get_version(3)>,
L<libnbd(3)>.

=head1 AUTHORS

Eric Blake

Richard W.M. Jones

=head1 COPYRIGHT

Copyright Red Hat
